### ISSUE TITLE
Imgur upload does not work

### ISSUE THREAD

**Issue by zunder** [carnager/teiler#18]
I did install teiler from AUR with imgur dependency. I also tried downloading the http://imgur.com/tools/imgurbash.sh file, which seems to be the same thing. I did not change teiler's config.

**Steps to reproduce:**

1. Start teiler from terminal
2. Go to Screenshot, hit Enter
3. Go to Area, hit Alt+1
4. Select the area

**Problem:**
all I get is a line telling me
```
[alex@localhost Downloads]$ teiler

Delete page:
```
If I additionally install xsel I get:
```
[alex@localhost Downloads]$ teiler

Delete page: 
Error: target STRING not available
Error: target STRING not available
```

Is that a known issue?

**Comment by carnager** [comment]
you need to rename the script to "imgur" (the header of the script actually says so)

**Comment by carnager** [comment]
seems imgur is broken. Not sure if this is temporary

```
carnager@caprica > imgur test.jpg

Delete page: 
```

**Comment by carnager** [comment]
AUR package updated...

**Comment by zunder** [comment]
That is some quick bugfixing. Thanks, now uploading works just fine.

Btw: `teiler --quick area` is already bound to a shortkey combination via i3 ;)

**Comment by Airblader** [comment]
The Readme now lists the wrong dependency.

**Comment by carnager** [comment]
thanks
