### ISSUE TITLE
Failed to save image ~/Pictures/Screenshots/img-2016-06-05-081334: no loader for file format (unsupported format)

### ISSUE THREAD

**Issue by fogine** [carnager/teiler#19]
On current master version when I try to take a screenshot I get Error message:
>Failed to save image $HOME/Pictures/Screenshots/img-2016-06-05-081334: no loader for file
>format (unsupported format)

For Teiler v3.0 screenshots works (however `rofiopts` option is ignored).

**Comment by carnager** [comment]
can you tell how exactly you went ahead? cannot reproduce

**Comment by carnager** [comment]
also show config

**Comment by fogine** [comment]
As I tried to reproduce the error after I deleted every file teiler installation process has created I've come to conclusion that it was the difference in config file that caused the error.

At first I installed teiler v3.0 which does not require `$img_filemask` option to have a file extension included (current master does). But after I found out that `v3.0` is ignoring `$rofiopts` I've installed current master version but did not overwrite/update the config file.

##### Improvement proposal:
Maybe it would be good idea to echo some message at installation process that the config format has changed and is not compatible/needs to be updated so people will get informed.

Thank you for sharing your work

**Comment by carnager** [comment]
this is a git package. changes are to be expected. on next release config changes will be mentioned.
