### ISSUE TITLE
area video capture does not work

### ISSUE THREAD

**Issue by FichteFoll** [carnager/teiler#29]
Using latest master, area video capture doesn't work.

The output from `slop` is eval'ed, but the output is `492x341+710+352`, for example, and that doesn't eval to anything. Following that, the geometry specification to ffmpeg gets messed up and it returns `:0+,: Invalid argument`. This happens regardless of whether I cancel the slop area selection or not.

Furthermore, the ffmpeg error is not interpreted and teiler thinks it is still running when I invoke the command again. Not sure if this is detectable with the current structure.

**Comment by carnager** [comment]
meh, maim/slop changed its complete arguments and outputs. Have to look into it.

**Comment by carnager** [comment]
Also fixed issues, when uneven slop results made ffmpeg choke with this commit.
