### ISSUE TITLE
Teiler area copy failing

### ISSUE THREAD

**Issue by mrcpj1998** [carnager/teiler#30]
While running teiler either from command line or rofi, any screenshot option using area returns an error:

    Maim encountered an error:
    Invalid argument '-y'

This problem is seen in the most recent commit with maim `v4.4.60`

**Comment by carnager** [comment]
update maim/slop

**Comment by mrcpj1998** [comment]
It seems the newest version hasn't hit Arch community repos yet; Thanks

**Comment by carnager** [comment]
Your maim version is up2date.  You just need a recent checkout of teiler

**Comment by mrcpj1998** [comment]
Ahh sorry; I seem to have made a mistake. I cloned the newest branch, but still managed to run the old version of teiler. Thanks for your time
