### ISSUE TITLE
Teiler does not work anymore

### ISSUE THREAD

**Issue by antoyo** [carnager/teiler#33]
Hello.
When I try to take a screenshot of the whole monitor (the same happens for a region) without delay using `teiler`, it does not work and I get the following error in the terminal:
```
Maim encountered an error:
Invalid argument `-y`.
```
I use ArchLinux and `maim` v4.4.61.
Thanks to fix this issue.

**Comment by carnager** [comment]
This is fixed since day one. just use teiler-git package. I should do a release some day again :)

**Comment by carnager** [comment]
Ok, made a release for this: https://github.com/carnager/teiler/releases/tag/3.1.2
