### ISSUE TITLE
screenshot is a bit slow

### ISSUE THREAD

**Issue by amosbird** [carnager/teiler#36]
When taking a screenshot with rectangle selection, I offer quickly switch to another window and paste it. However, the resulting screenshot sometimes is taken from the new window that I switch to.

**Comment by carnager** [comment]
hmm, just tried it. ran `teiler --quick image area`, drew a rectangle and instantly switched workspace. couldnt manage to switch fast enough for it to screenshot the new workspace...

**Comment by carnager** [comment]
for completeness: This is the code that it run:
`maim $cursor ${rect_border} ${rect_color} -s "${img_path}/${3}";`

I set no delay whatsoever

**Comment by amosbird** [comment]
@carnager well it's not always reproducable. I've encountered a bunch of times though, mainly when trying to paste a screenshot url into irc and people saying wrong url ...

**Comment by carnager** [comment]
anyway, since all i do is call maim, I don't think this is fixable in teiler.
