### ISSUE TITLE
Error: Segmentation fault

### ISSUE THREAD

**Issue by fogine** [carnager/teiler#37]
I've installed `teiler-git` package from `aur`.

When I start teiler simply with `teiler` command it exits emidiately with error:

```bash
> teiler
(process:4823): GLib-CRITICAL **: g_timer_elapsed: assertion 'timer != NULL' failed                                    
/usr/sbin/teiler: line 406:  4823 Segmentation fault      (core dumped) rofi -kb-move-word-forward '' -dmenu "$@"
```
exit code = 0

After some debugging I've found that the following code from `teiler` bash script starting at line 37 is what causes the exception:

```bash
if [[ -d /etc/teiler ]]
then
  cd /etc/teiler/profiles
  for i in *; do
    if [[ ! -f $HOME/.config/teiler/profiles/"$i" ]]; then
      cp /etc/teiler/profiles/"$i" $HOME/.config/teiler/profiles
    else
      cmp "$i" $HOME/.config/teiler/profiles/"$i" || cp -f /etc/teiler/profiles/"$i" $HOME/.config/teiler/profiles
    fi
  done
fi
```

```bash
> uname -a

Linux myuser 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux

```

**Comment by carnager** [comment]
First of all it's rofi segfaulting, not bash.
And the pasted codeblock does not even call rofi, so it's very unlikely that it's related.

Offtopic: Why is teiler in /usr/sbin?

**Comment by fogine** [comment]
My thinking was same, however only way how to get rid off the failure is to comment the if block, then everything works as it's supposed to.

On the other hand if I comment out `rofi` execution, the error does not occur.
Also if I run the exact same `rofi` command in user shell (outside of teiler script), it works...:

```bash
> echo -e "< Exit\n---\n1 [ Screenshots ]>\n2 [ Screencasts ]>\n3 [ History ]>\n---\n4 Pastebin Text from Clipboard" | rofi -kb-move-word-forward '' -dmenu -kb-accept-alt '' -kb-move-word-forward '' -u 2 -p 'teiler>'
```

I used `yaourt` to install the `aur` package. For some reason it installs it into `sbin` which is bad (dont know currently why) but should not make any difference in context of this issue.

```bash
> rofi -v
Version: 1.3.1 - 1.3.1-685-g4d728e3c (master)
```

**Comment by carnager** [comment]
SO you are on arch? I am too and most users I know are too. Never heard of this issue before, this is strange.

**Comment by fogine** [comment]
I'm migrated to arch quite recently viz. `uname -a` output. 

>Not that it matters, since arch only has /usr/bin + symlinks, but this seems rather odd.

That actually explains it, as I did not notice that `sbin` directories are just symlinks, thanks.
In my `PATH`, `/usr/sbin` is before `/usr/bin`. 

I've reinstalled the `teiler-git` package. Once again, I get segmentation error:

```bash
> teiler

(process:31932): GLib-CRITICAL **: g_timer_elapsed: assertion 'timer != NULL' failed                                   
/etc/teiler/teiler.conf: line 4: 31932 Segmentation fault      (core dumped) rofi -kb-accept-entry "!Return" "$@"
```

When I run:

```bash
> echo -e "< Exit\n---\n1 [ Screenshots ]>\n2 [ Screencasts ]>\n3 [ History ]>\n---\n4 Pastebin Text from Clipboard" | rofi -kb-accept-entry '!Return' -dmenu -p "teiler > "
```
It runs without an error.

Still, when I comment out [SAME](https://github.com/carnager/teiler/blob/master/teiler#L42) if block, teiler works as expected.  
if I leave the if block uncommented and replace [THIS](https://github.com/carnager/teiler/blob/master/teiler#L5) and [THIS](https://github.com/carnager/teiler/blob/master/config.example#L5) line by just `return 0` than no error occurs:

```bash
> teiler #rofi execution replaced with "return 0"
> 
> echo $?
0
>
```

Along `teiler` I use `rofi` with quite few other scripts. So far I've never got similar error when using the other ones.

**Comment by carnager** [comment]
soooo... does this crash too?

```
#!/usr/bin/env bash

_rofi () {
  rofi -kb-accept-entry "!Return" "$@"
}

echo "test" | _rofi -dmenu
```

**Comment by fogine** [comment]
Yeah, should have updated to upstream `rofi` before creating this issue. Sorry. And thanks for support.

**Comment by carnager** [comment]
No problem. 1.4 will hopefully be out soon.
