### ISSUE TITLE
Image Contains No Data

### ISSUE THREAD

**Issue by Dobbie03** [carnager/teiler#42]
Once a screenshot has been taking, opening the file to view produces an error saying that the image file contains no data.
Using on ArchLabs Linux.

**Comment by Dobbie03** [comment]
This is the output from the terminal

`/usr/bin/teiler: line 340:  7531 Aborted                 (core dumped) maim $cursor -d ${delay} "${img_path}/${3}"`

**Comment by carnager** [comment]
This is a maim bug. Already fixed upstream, wait for 5.5.1 Release or build maim-git from AUR.
