### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by chabad360** [carnager/teiler#46]
Can you add `eog` and `copyq` dependencies, they're needed for some basic functionality.

**Comment by carnager** [comment]
eog is not a dependency. The image viewer can be set in config file. I can list copyq as a dep in the README though

**Comment by chabad360** [comment]
> The image viewer can be set in config file.

Oh ok, good to know.

> I can list copyq as a dep in the README though

that would be great! Thanks!

**Comment by chabad360** [comment]
There: #47

**Comment by chabad360** [comment]
thanks
