### ISSUE TITLE
Exclude blur on area class?

### ISSUE THREAD

**Issue by Laks0** [carnager/teiler#54]
Hi, I'm using background blur with Picom and when I try to take an area screenshot, the whole screen gets affected by the blur. I would like to exclude the area selection from the blur background but I don't know what condition to use. Is there a window class or role or title or something like that that I could use to identify the area selection?

**Comment by Walbaum** [comment]
You need to exclude "class_g = 'slop'" from having shadows or blur effects.

**Comment by Laks0** [comment]
Thanks! that worked. closing.
