### ISSUE TITLE
dmenu support and must-have dep rofi-git

### ISSUE THREAD

**Issue by shibumi** [carnager/teiler#7]
Hello,
First of all you should add rofi-git as dependency instead of opt-dep. The script will fail without rofi.

what happened to dmenu support? How can I adjust the menu in the top instead of in the middle of the screen?

**Comment by carnager** [comment]
dmenu support is gone since it does not support the multi-key features needed for later releases.
rofi has the -location switch. simply add that to the rofiopts config option.
